
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'canvas_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'canvas_dbt'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

dispatch:
  - macro_namespace: fivetran_utils
    search_order: ['spark_utils', 'fivetran_utils']
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'fivetran_utils', 'dbt_utils']

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    - "dbt_packages"

sources:
  canvas_dbt:

vars:
# Hubpost source
## MKT source
  email_metrics: ['sends', 'bounces', 'clicks', 'deferrals', 'deliveries', 'drops', 'forwards', 'opens', 'prints', 'spam_reports']
  contact_form_submission_enabled: true
  contact_list_member_enabled: true
  contact_list_enabled: true
  contact_enabled: true
  email_campaign_enabled: true
  email_event_enabled: true
  email_subscription_change_enabled: true
  email_subscription_enabled: true

## Sales source
  hubspot__engagement: true
  hubspot__engagement_contact: true
  hubspot__engagement_deal: true
  hubspot__deal: true
  hubspot__deal_pipeline: true
  hubspot__deal_stage: true
  hubspot__deal_pipeline_stage: true
  hubspot__engagement_company: true
  hubspot__company: true

# HubSpot passthrough columns
  hubspot__company_pass_through_columns: []
  hubspot__pass_through_all_columns: false # overwrite any passthrough columns var by just passing all columns
  hubspot__owner: true

# Google analytics source
  ga_adwords_campaigns_enabled: true
  ga_adwords_hourly_stats_enabled: true
  ga_adwords_keyword_enabled: true
  ga_audience_overview_enabled: true
  ga_browser_and_operating_system_overview_enabled: true
  ga_campaign_performance_enabled: true
  ga_channel_traffic_enabled: true
  ga_events_overview_enabled: true
  ga_social_media_acquisitions_enabled: true
  ga_traffic_enabled: true

# Ads source
  ## Linkedin
  ad_reporting__linkedin_ads_enabled: true
  linkedin__use_local_currency: false
  linkedin__passthrough_metrics: []
  ## Microsoft
  ad_reporting__microsoft_ads_enabled: true
  microsoft_auto_tagging_enabled: false
  ## Pinterest
  ad_reporting__pinterest_enabled: true
  pin_promotion_report_pass_through_metric: []
  ## Google 
  ad_reporting__google_ads_enabled: true
  google_ads__ad_stats_passthrough_metrics: []
  ## Twitter
  ad_reporting__twitter_ads_enabled: true
  ## Facebook
  ad_reporting__facebook_ads_enabled: true
  ## Snapchat
  ad_reporting__snapchat_ads_enabled: true
  ## Tiktok
  ad_reporting__tiktok_ads_enabled: true

# Salesforce
  salesforce__user_role_enabled: true
  salesforce__user_enabled: true
  salesforce__account_enabled: true
  salesforce__opportunity_enabled: true

 # Salesforce pass through column variables
  account_pass_through_columns: []
  opportunity_pass_through_columns: []
  user_role_pass_through_columns: []
  user_pass_through_columns: []

# Zendesk
  zendesk__ticket_passthrough_columns: []
  zendesk__ticket_field_history: true
  zendesk__organization_tag: false
  zendesk__domain_names: false

# Marketo
  marketo__activity_change_data_value: true
  marketo__activity_click_email: true 
  marketo__activity_delete_lead_enabled: true 
  marketo__activity_email_bounced: true
  marketo__activity_email_delivered: true 
  marketo__activity_merge_leads: true 
  marketo__activity_open_email: true 
  marketo__activity_send_email: true 
  marketo__activity_unsubscribe_email: true 
  marketo__campaign: true
  marketo__email_template_history: true 
  marketo__lead_describe: true
  marketo__lead: true 
  marketo__program: true 

  # Outreach
  outreach_account: true
  outreach_opportunity: false

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  canvas_dbt:
    materialized: table
    +database: 'JOON_SOLUTIONS'

    staging:
      +required_tests: {"unique.*|not_null": 2}
      +materialized: table

    intermediate:
      +required_tests: {"unique.*|not_null|at_least_one": 3}
      +materialized: table
      
    mart:
      +required_tests: {"unique.*|not_null|at_least_one": 3}
      +materialized: table

