
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'canvas_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'canvas_dbt'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

sources:
  canvas_dbt:

seeds:
  schema: analytics

vars:
  # RE_DATA
  email_metrics: ['bounces', 'clicks', 'deferrals', 'deliveries', 'drops', 'forwards', 'opens', 'prints', 'spam_reports', 'unsubscribes']

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  canvas_dbt:
    materialized: table
    +database: 'ANALYTICS'

    re_data:
      +schema: re_data
    
    base:
      +required_tests: {"unique.*|not_null": 2}
      +materialized: table

    intermediate:
      +required_tests: {"unique.*|not_null|at_least_one": 3}
      +materialized: table
      
    mart:
      +required_tests: {"unique.*|not_null|at_least_one": 3}
      +materialized: table

