canvas_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: om37979.ap-southeast-1
      # Replace by your user/password or set the environment variables
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"

      role: TRANSFORMER
      database: ANALYTICS
      warehouse: COMPUTE_WH
      # Replace with dbt_yourname or set environment variable DBT_SCHEMA
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 10
      client_session_keep_alive: False