canvas_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: vta74817
      # Replace by your user/password or set the environment variables
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"

      role: JOON_SOLUTIONS_ROLE
      database: JOON_SOLUTIONS
      warehouse: COMPUTE_WH
      # Replace with dbt_yourname or set environment variable DBT_SCHEMA
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 10
      client_session_keep_alive: False