with source as (

    select * from {{ source('hubspot', 'company') }}

),

renamed as (

    select
        id,
        portal_id,
        is_deleted,
        _fivetran_synced,
        property_hs_analytics_source_data_2,
        property_num_conversion_events,
        property_hs_analytics_num_page_views,
        property_hs_analytics_source_data_1,
        property_hs_num_decision_makers,
        property_hs_num_open_deals,
        property_num_associated_contacts,
        property_hs_num_blockers,
        property_hs_analytics_first_timestamp,
        property_hs_num_contacts_with_buying_roles,
        property_first_conversion_event_name,
        property_hs_analytics_num_visits,
        property_recent_conversion_event_name,
        property_hs_analytics_last_visit_timestamp,
        property_hs_analytics_source,
        property_hs_lastmodifieddate,
        property_founded_year,
        property_recent_conversion_date,
        property_hs_target_account_probability,
        property_hs_analytics_first_visit_timestamp,
        property_is_public,
        property_timezone,
        property_hs_analytics_last_timestamp,
        property_first_conversion_date,
        property_hs_last_logged_call_date,
        property_total_money_raised,
        property_city,
        property_description,
        property_domain,
        property_hs_num_child_companies,
        property_industry,
        property_zip,
        property_website,
        property_facebook_company_page,
        property_state,
        property_web_technologies,
        property_name,
        property_linkedinbio,
        property_address,
        property_createdate,
        property_linkedin_company_page,
        property_country,
        property_twitterhandle,
        property_annualrevenue,
        property_first_contact_createdate,
        property_numberofemployees,
        property_phone,
        property_address_2,
        property_num_notes,
        property_notes_last_contacted,
        property_notes_last_updated,
        property_num_contacted_notes,
        property_notes_next_activity_date,
        property_hs_latest_meeting_activity,
        property_hs_last_booked_meeting_date,
        property_hs_sales_email_last_replied,
        property_hs_last_sales_activity_timestamp,
        property_hs_last_sales_activity_date,
        property_hs_last_open_task_date,
        property_num_associated_deals,
        property_hs_pipeline,
        property_hs_total_deal_value,
        property_hubspot_owner_id,
        property_first_deal_created_date,
        property_hs_updated_by_user_id,
        property_hs_user_ids_of_all_owners,
        property_hs_created_by_user_id,
        property_hs_all_owner_ids,
        property_lifecyclestage,
        property_hubspot_owner_assigneddate,
        property_company_pipedrive_create_date,
        property_organization_type,
        property_relationship_type,
        property_pipedrive_company_id,
        property_type,
        property_hubspot_team_id,
        property_hs_all_team_ids,
        property_hs_all_accessible_team_ids,
        property_lead_source_pick_list,
        property_closedate,
        property_recent_deal_close_date,
        property_hs_merged_object_ids,
        property_recent_deal_amount,
        property_total_revenue,
        property_hs_additional_domains,
        property_days_to_close,
        property_hs_lead_status,
        property_hub_category,
        property_hs_parent_company_id,
        property_hs_analytics_last_touch_converting_campaign,
        property_hs_analytics_first_touch_converting_campaign

    from source

)

select * from renamed