with source as (

    select * from {{ source('hubspot', 'deal') }}

),

renamed as (

    select
        deal_id,
        portal_id,
        is_deleted,
        is_merged,
        _fivetran_synced,
        property_hs_analytics_source_data_2,
        property_hs_analytics_source,
        property_hs_analytics_source_data_1,
        property_hs_closed_amount_in_home_currency,
        property_hs_closed_amount,
        property_amount_in_home_currency,
        property_hs_created_by_user_id,
        property_days_to_close,
        property_hs_date_entered_appointmentscheduled,
        property_hs_deal_stage_probability,
        property_hs_projected_amount,
        property_hs_priority,
        property_hs_lastmodifieddate,
        property_hs_projected_amount_in_home_currency,
        property_hs_num_target_accounts,
        property_hs_deal_stage_probability_shadow,
        property_dealtype,
        property_hs_time_in_appointmentscheduled,
        owner_id,
        property_hs_updated_by_user_id,
        deal_pipeline_id,
        property_hubspot_owner_assigneddate,
        property_dealname,
        property_closedate,
        property_createdate,
        deal_pipeline_stage_id,
        property_amount,
        property_hs_createdate,
        property_hs_user_ids_of_all_owners,
        property_hs_all_owner_ids,
        property_num_notes,
        property_num_contacted_notes,
        property_notes_last_contacted,
        property_notes_next_activity_date,
        property_hs_latest_meeting_activity,
        property_notes_last_updated,
        property_contact_person,
        property_from_pipeline,
        property_status,
        property_pipedrive_deal_id,
        property_hs_next_step,
        property_hs_forecast_probability,
        property_hubspot_team_id,
        property_closed_lost_reason,
        property_label,
        property_hs_all_team_ids,
        property_hs_all_accessible_team_ids,
        property_subscription_length,
        property_relationship_type,
        property_n_1_time_revenue,
        property_business_segment,
        property_opportunity_size,
        property_executive_sponsor,
        property_hs_sales_email_last_replied,
        property_hs_is_closed,
        property_go_live_date,
        property_hs_is_closed_won,
        property_description,
        property_referral_source,
        property_trial_end_date,
        property_trial_start_date,
        property_number_of_licenses,
        property_product,
        property_end_date,
        property_custom,
        property_other_fee_amount,
        property_fee_type,
        property_pepy_fee,
        property_start_date,
        property_hs_merged_object_ids,
        property_pepm_rate,
        property_company_name

    from source

)

select * from renamed