{{ config(enabled = var('contact_enabled') ) }}

with source as (

    select * from {{ source('hubspot', 'contact') }}

),

renamed as (

    select
        id as contact_id,
        canonical_vid,
        merged_vids,
        _fivetran_deleted,
        property_business_type,
        property_cohort,
        property_company_logo,
        property_company_size,
        property_date_of_birth,
        property_degree,
        property_field_of_study,
        property_gender,
        property_graduation_date,
        property_how_did_you_hear_about_us_,
        property_hs_all_assigned_business_unit_ids,
        property_hs_analytics_first_touch_converting_campaign,
        property_hs_analytics_last_touch_converting_campaign,
        property_hs_avatar_filemanager_key,
        property_hs_buying_role,
        property_hs_content_membership_notes,
        property_hs_content_membership_registration_domain_sent_to,
        property_hs_content_membership_status,
        property_hs_conversations_visitor_email,
        property_hs_email_customer_quarantined_reason,
        property_hs_email_hard_bounce_reason,
        property_hs_email_hard_bounce_reason_enum,
        property_hs_email_quarantined_reason,
        property_hs_emailconfirmationstatus,
        property_hs_facebook_click_id,
        property_hs_facebookid,
        property_hs_feedback_last_nps_follow_up,
        property_hs_feedback_last_nps_rating,
        property_hs_google_click_id,
        property_hs_googleplusid,
        property_hs_ip_timezone,
        property_hs_lead_status,
        property_hs_legal_basis,
        property_hs_linkedinid,
        property_hs_marketable_reason_id,
        property_hs_marketable_reason_type,
        property_hs_marketable_status,
        property_hs_marketable_until_renewal,
        property_hs_merged_object_ids,
        property_hs_pipeline,
        property_hs_predictivescoringtier,
        property_hs_testpurge,
        property_hs_testrollback,
        property_hs_timezone,
        property_hs_twitterid,
        property_hs_unique_creation_key,
        property_hs_user_ids_of_all_notification_followers,
        property_hs_user_ids_of_all_notification_unfollowers,
        property_hs_user_ids_of_all_owners,
        property_i_m_interested_in,
        property_industry_2,
        property_ip_city,
        property_ip_country,
        property_ip_country_code,
        property_ip_latlon,
        property_ip_state,
        property_ip_state_code,
        property_ip_zipcode,
        property_job_function,
        property_marital_status,
        property_military_status,
        property_n_092921_webinar,
        property_name as contact_name,
        property_provider_type,
        property_relationship_status,
        property_school,
        property_seniority,
        property_start_date,
        property_where_did_you_hear_about_us_first_,
        property_work_email,
        property_your_message,
        property_your_name,
        property_zoom_webinar_joinlink,
        property_firstname,
        property_hs_analytics_first_url,
        property_hs_email_optout_11276246,
        property_hs_email_optout_16460835,
        property_hs_email_optout_16460882,
        property_hs_email_optout_20892955,
        property_hs_email_optout_21234221,
        property_twitterhandle,
        property_currentlyinworkflow,
        property_hs_analytics_last_url,
        property_lastname,
        property_salutation,
        property_twitterprofilephoto,
        property_email as contact_email,
        property_hs_persona,
        property_mobilephone,
        property_phone,
        property_fax,
        property_hs_email_last_email_name,
        property_address as contact_address,
        property_engagements_last_meeting_booked_campaign,
        property_engagements_last_meeting_booked_medium,
        property_engagements_last_meeting_booked_source,
        property_hubspot_owner_id,
        property_owneremail,
        property_ownername,
        property_city as contact_city,
        property_hubspot_team_id,
        property_linkedinbio,
        property_twitterbio,
        property_hs_all_owner_ids,
        property_state,
        property_hs_all_team_ids,
        property_hs_analytics_source as analytics_source,
        property_hs_latest_source,
        property_zip,
        property_country as contact_country,
        property_hs_all_accessible_team_ids,
        property_hs_analytics_source_data_1,
        property_hs_latest_source_data_1,
        property_hs_analytics_source_data_2,
        property_hs_language,
        property_hs_latest_source_data_2,
        property_hs_analytics_first_referrer,
        property_jobtitle as contact_job_title,
        property_photo,
        property_hs_analytics_last_referrer,
        property_message,
        property_lifecyclestage,
        property_company as contact_company,
        property_website,
        property_numemployees,
        property_annualrevenue,
        property_industry,
        property_hs_predictivecontactscorebucket,
        property_hs_email_first_send_date,
        property_hs_analytics_revenue,
        property_hs_is_unworked,
        property_hs_analytics_average_page_views,
        property_associatedcompanyid,
        property_hs_analytics_num_event_completions,
        property_hs_analytics_first_timestamp,
        property_hs_email_delivered,
        property_hs_social_facebook_clicks,
        property_hs_social_google_plus_clicks,
        property_hs_social_linkedin_clicks,
        property_hs_analytics_num_page_views,
        property_hs_email_last_send_date,
        property_lastmodifieddate,
        property_hs_social_num_broadcast_clicks,
        property_hs_analytics_num_visits,
        property_hs_email_sends_since_last_engagement,
        property_hs_lifecyclestage_lead_date,
        property_createdate as created_at,
        property_hs_social_twitter_clicks,
        _fivetran_synced,
        property_hs_lifecyclestage_subscriber_date,
        property_hs_email_first_click_date,
        property_hs_email_first_open_date,
        property_hs_email_last_click_date,
        property_hs_email_click,
        property_hs_email_open,
        property_hs_email_last_open_date,
        property_hs_email_bounce,
        property_hs_analytics_last_visit_timestamp,
        property_hs_analytics_first_visit_timestamp,
        property_hs_analytics_last_timestamp,
        property_zoom_webinar_registration_count,
        property_hs_count_is_worked,
        property_hs_count_is_unworked,
        property_hubspot_owner_assigneddate,
        property_surveymonkeyeventlastupdated,
        property_hs_email_optout,
        property_zoom_webinar_attendance_average_duration,
        property_notes_last_updated,
        property_zoom_webinar_attendance_count,
        property_num_notes,
        property_notes_last_contacted,
        property_num_contacted_notes,
        property_number_of_employees,
        property_hs_social_last_engagement,
        property_hs_email_bad_address,
        property_hs_lifecyclestage_marketingqualifiedlead_date,
        property_hs_sequences_actively_enrolled_count,
        property_hs_email_optout_25376496,
        property_notes_next_activity_date,
        property_hs_latest_meeting_activity,
        property_hs_sales_email_last_replied,
        property_hs_last_sales_activity_timestamp,
        property_hs_last_sales_activity_date,
        property_hs_sales_email_last_opened,
        property_hs_created_by_conversations,
        property_hs_sa_first_engagement_date,
        property_engagements_last_meeting_booked,
        property_anticipated_number_of_users,
        property_lead_type,
        property_executive_assistant_phone_number,
        property_subject_matter_expertise,
        property_executive_assistant_email_address,
        property_logo_file,
        property_executive_assistant_name,
        property_hs_facebook_ad_clicked,
        property_partner_level,
        property_num_associated_deals,
        property_first_deal_created_date,
        property_hs_time_between_contact_creation_and_deal_creation,
        property_hs_lifecyclestage_opportunity_date,
        property_hs_email_last_reply_date,
        property_hs_email_first_reply_date,
        property_hs_email_replied,
        property_custom_num_notes,
        property_custom_create_date,
        property_pipedrive_person_id,
        property_vip_contact,
        property_hs_sales_email_last_clicked,
        property_closedate,
        property_recent_deal_close_date,
        property_hs_lifecyclestage_salesqualifiedlead_date,
        property_hs_time_between_contact_creation_and_deal_close,
        property_hs_time_to_move_from_subscriber_to_customer,
        property_hs_time_to_move_from_opportunity_to_customer,
        property_recent_deal_amount,
        property_hs_lifecyclestage_customer_date,
        property_total_revenue,
        property_hs_time_to_move_from_lead_to_customer,
        property_which_partner_tier_are_you_interested_in_,
        property_hs_latest_source_timestamp,
        property_hs_email_optout_34806415,
        property_hs_email_optout_34863456,
        property_how_can_we_assist_you_,
        property_if_other_please_describe_your_inquiry_below_,
        property_hs_linkedin_ad_clicked,
        property_hs_clicked_linkedin_ad,
        property_hs_created_by_user_id

    from source

)

select * from renamed

